name: cmo_ferry
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  lottie: 2.3.2
  google_fonts: 4.0.3
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+4
  fluttertoast: ^8.2.1
  image: 4.0.16
  flutter_flavorizr: 2.1.6
  change_app_package_name: 1.1.0
  sliding_clipped_nav_bar: 3.1.0+4
  salomon_bottom_bar: 3.3.2
  font_awesome_flutter: 10.4.0
  dartz: ^0.10.1
  easy_stepper: any
  octo_image: 1.0.2
  flag: 6.0.0
  auto_size_text: 3.0.0
  get_storage: 2.1.1
  dropdown_button2: 2.1.2
  package_info_plus: ^3.0.1
  intl: 0.18.1
  dotted_border: ^2.0.0+3
  logger: 1.3.0
  pretty_dio_logger: ^1.2.0-beta-1
  alice: ^0.3.2
  syncfusion_flutter_datepicker: 19.4.38
  get_it: 7.6.0
  flutter_secure_storage: 8.0.0
  material_design_icons_flutter: 6.0.7096
  geolocator: ^9.0.2
  pull_to_refresh: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies: 
  retrofit_generator: any
  build_runner: any
  json_serializable: any
  flutter_lints: 2.0.1
  flutter_launcher_icons: 0.13.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/logo/cmo_ferry_logo.png
  adaptive_icon_foreground: assets/logo/cmo_ferry_logo_foreground.png
  adaptive_icon_background: assets/logo/cmo_ferry_logo_background.png
  ios: true

flutter: 
  assets: 
    - assets/anim/
    - assets/logo/
    - assets/images/
  fonts: 
    - family: NotoSans
      fonts: 
        - asset: fonts/NotoSans-Regular.ttf
    - family: NotoSansMyanmar
      fonts: 
        - asset: fonts/NotoSansMyanmar-Regular.ttf
  uses-material-design: true

flavorizr: 
  app: 
    android: 
      flavorDimensions: flavor-type
    ios: null
  flavors: 
    staging: 
      app: 
        name: Staging CMO Ferry
      android: 
        applicationId: mm.com.cmoit.cmo_ferry.staging
      ios: 
        bundleId: mm.com.cmoit.cmo_ferry.staging
    prod: 
      app: 
        name: CMO Driver
      android: 
        applicationId: mm.com.cmoit.cmo_ferry
      ios: 
        bundleId: mm.com.cmoit.cmo_ferry

